Add `Show-InvokeGitReturn`: fixes Issue #90
dsccommunity/DscResource.DocGenerator pull request #96
Opened 2021-07-10 00:04 UTC by phbits

# Pull Request

### Pull Request (PR) description
Adds function `Show-InvokeGitReturn` to improve error handling when using `Invoke-Git`.

#### This Pull Request (PR) fixes the following issues
- Fixes #90

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Documentation added/updated in README.md.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated.
- [x] Integration tests added/updated (where possible).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2021-07-10 05:15 UTC, phbits commented
@johlju - Here's my fix to add better error handling around `Invoke-Git`. It successfully goes through `build` and `test`; however, I need to test in Azure Pipelines and somehow test publishing. 🤔 Even though there's still work to do, I wanted to open a PR to see if you have any feedback. In fact, as I'm typing this some of the checks are already finished as failed. 👷‍♂️

2021-07-10 12:03 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @phbits)

___
*[source/Private/Show-InvokeGitReturn.ps1, line 81 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFFOEhAHRzTRMSKOqc:-MeFFOEhAHRzTRMSKOqd:b-a0z8tf) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Private/Show-InvokeGitReturn.ps1#L81)):*
> ```
> Write-Debug -Message ($script:localizedData.InvokeGitCommandDebug -f $Command)
> ```

Maybe we should make sure to redact any tokens in the command before outputting it. If this function is used separately in other parts of code later it is easily missed that it will output tokens. We should try to mitigate that happening?
___
*[source/Public/Publish-WikiContent.ps1, line 147 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFGGaQ91ZHl26cSRcD:-MeFGGaQ91ZHl26cSRcE:b-253dnj) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L147)):*
> ```
> $tempPath.FullName
> ```

Should not have `Fullname` here, it is already taken care of at line 105.
___
*[source/Public/Publish-WikiContent.ps1, line 149 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFHHqQ04NjiexOAaGs:-MeFHHqQ04NjiexOAaGt:bk89ddc) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L149)):*
> ```
> if ($gitLocalResult.ExitCode -ne 0)
> ```

If `$VerbosePreference` or `$DebugPreference`  is not `'SilentyContinue'` then we should run `Show-InvokeGitReturn` even when exit code is 0, because then the user want debug and or verbose information.  Throughout.
___
*[source/Public/Publish-WikiContent.ps1, line 157 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFGMCd3q1rrtNg26Kz:-MeFGMCd3q1rrtNg26L-:b-q0qr9c) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L157)):*
> ```
> $gitAddResult = Invoke-Git -WorkingDirectory $tempPath.FullName `
> ```

Should not have `Fullname` here, it is already taken care of at line 105.
___
*[source/Public/Publish-WikiContent.ps1, line 164 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFGNa31DnRjKHqIYf4:-MeFGNa31DnRjKHqIYf5:bsg5u0e) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L164)):*
> ```
>  $gitCommitResult = Invoke-Git -WorkingDirectory $tempPath.FullName `
> ```

Should not have `Fullname` here, it is already taken care of at line 105.
___
*[source/Public/Publish-WikiContent.ps1, line 174 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFGuH0AMyhTPIZlrTc:-MeFGuH0AMyhTPIZlrTd:bjj4c37) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L174)):*
> ```
> 'PushModuleVersion' 
> ```

Should be `PushTag` (tag is the module version)
___
*[source/Public/Publish-WikiContent.ps1, line 180 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFHqrr2wYNrjkqbcgZ:-MeFHqrr2wYNrjkqbcg_:ba00vst) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L180)):*
> ```
> $tempPath.FullName 
> ```

Should not have `Fullname` here, it is already taken care of at line 105.


<!-- Sent from Reviewable.io -->

2021-07-10 12:05 UTC, johlju commented
Thanks for this PR! This is my initial review looking through it, I found some things, but will look deeper into it once these comments are resolved. 🙂

2021-07-11 12:43 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @phbits)

___
*[source/Public/Invoke-Git.ps1, line 89 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKTQsA9NNJB-wHQm1e:-MeKTQsA9NNJB-wHQm1f:bsgro2e) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Invoke-Git.ps1#L89)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>                 if ($gitResult.StandardOutput -match ':[\d|a-f].*@')
>                 {
>                     $gitResult.StandardOutput = $gitResult.StandardOutput -replace ':[\d|a-f].*@', ':RedactedToken@'
>                 }
>                 if ($gitResult.StandardError -match ':[\d|a-f].*@')
>                 {
>                     $gitResult.StandardError = $gitResult.StandardError -replace ':[\d|a-f].*@', ':RedactedToken@'
>                 }
> ```
</details>


Is this needed, is the token outputted in error message or output messages by `git` (and in this format the regex looks for)? 
___
*[source/Public/Publish-WikiContent.ps1, line 113 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKQOvL3ZEaeR9oJQud:-MeKQOvL3ZEaeR9oJQue:b-rfufdu) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Publish-WikiContent.ps1#L113)):*
> ```
> for ($i=0; $i -lt 20; $i++)
> ```

I don't really see the need for a for-loop here. This seems to just add unnecessary complexity to the function, and just makes it harder to debug. IMHO this looks like bad coding practice. :slightly_smiling_face: 
___
*[source/Public/Publish-WikiContent.ps1, line 204 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKRlbTBLbnT8awhT34:-MeKRlbTBLbnT8awhT35:bg7oi60) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Publish-WikiContent.ps1#L204)):*
> ```
> $invokeGitResult.ExitCode -ne 0
> ```

This function need to throw an error if the specific command returns an exit code that is not expected for the specific git command. The function should not just exit without an error in the middle of the run. So we need to add a check for exit code after each call to `Invoke-Git` and make sure to throw an error that is returned from git.


<!-- Sent from Reviewable.io -->

2021-07-12 23:18 UTC, phbits reviewed
Thanks for the feedback! There's a failing test that I need to resolve but wanted to go ahead and publish it to continue our dialog. :slightly_smiling_face:  

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-:-MeRxb8q5DeoNQ_XnvNT:b-pmmg1v)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @johlju)

___
*[source/Private/Show-InvokeGitReturn.ps1, line 81 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFFOEhAHRzTRMSKOqc:-MeGAmV2-M9YJ_V_SPP1:bho3zi3) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Private/Show-InvokeGitReturn.ps1#L81)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Write-Debug -Message ($script:localizedData.InvokeGitCommandDebug -f $Command)
> ```

Maybe we should make sure to redact any tokens in the command before outputting it. If this function is used separately in other parts of code later it is easily missed that it will output tokens. We should try to mitigate that happening?
</blockquote></details>

Good call. :thumbsup: The token should be scrubbed via your regex `if` statement. However, it would be good to ensure the token doesn't get displayed in `StandardOutput` or `StandardError`. I've incorporated this into `Invoke-Git` as noted in the next comment. I could update this section to use the same technique used for `StandardOutput`/`StandardError` (shown below) if you'd like.
___
*[source/Public/Invoke-Git.ps1, line 89 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKTQsA9NNJB-wHQm1e:-MeQGkEX83Pa8jz96ykS:b-mft8hp) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Invoke-Git.ps1#L89)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                 if ($gitResult.StandardOutput -match ':[\d|a-f].*@')
>                 {
>                     $gitResult.StandardOutput = $gitResult.StandardOutput -replace ':[\d|a-f].*@', ':RedactedToken@'
>                 }
>                 if ($gitResult.StandardError -match ':[\d|a-f].*@')
>                 {
>                     $gitResult.StandardError = $gitResult.StandardError -replace ':[\d|a-f].*@', ':RedactedToken@'
>                 }
> ```

Is this needed, is the token outputted in error message or output messages by `git` (and in this format the regex looks for)? 
</blockquote></details>

You had a good point to scrub any tokens from the command which gave me the idea that `StandardOutput` and `StandardError` should be checked too. I'm not entirely sure if this will catch all interactions of what `git` returns but thought it was a good place to start. Your git-foo is far superior so I'm open to any feedback.

After thinking about this for a bit, `$GitHubToken` should accessible since it's set in the environment. By checking for its presence, we can then check if it's been used.
___
*[source/Public/Publish-WikiContent.ps1, line 147 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFGGaQ91ZHl26cSRcD:-MeGAiujDe6srnDAzOTk:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L147)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $tempPath.FullName
> ```

Should not have `Fullname` here, it is already taken care of at line 105.
</blockquote></details>

Done.
___
*[source/Public/Publish-WikiContent.ps1, line 149 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFHHqQ04NjiexOAaGs:-MeFr5rbCo6XBkaB5GbO:bcqdjld) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L149)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($gitLocalResult.ExitCode -ne 0)
> ```

If `$VerbosePreference` or `$DebugPreference`  is not `'SilentyContinue'` then we should run `Show-InvokeGitReturn` even when exit code is 0, because then the user want debug and or verbose information.  Throughout.
</blockquote></details>

I'll refactor things and move this functionality to `Invoke-Git`.
___
*[source/Public/Publish-WikiContent.ps1, line 157 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFGMCd3q1rrtNg26Kz:-MeGB2fiE_jOTEVbJ-Qq:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L157)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $gitAddResult = Invoke-Git -WorkingDirectory $tempPath.FullName `
> ```

Should not have `Fullname` here, it is already taken care of at line 105.
</blockquote></details>

Done.
___
*[source/Public/Publish-WikiContent.ps1, line 164 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFGNa31DnRjKHqIYf4:-MeGB4ZR-A9BC_NtuT4r:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L164)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>  $gitCommitResult = Invoke-Git -WorkingDirectory $tempPath.FullName `
> ```

Should not have `Fullname` here, it is already taken care of at line 105.
</blockquote></details>

Done.
___
*[source/Public/Publish-WikiContent.ps1, line 174 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFGuH0AMyhTPIZlrTc:-MeGq8bFD0y6e8t1WIrD:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L174)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'PushModuleVersion' 
> ```

Should be `PushTag` (tag is the module version)
</blockquote></details>

Done.
___
*[source/Public/Publish-WikiContent.ps1, line 180 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFHqrr2wYNrjkqbcgZ:-MeGBCxe76Gxsh717gN_:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Public/Publish-WikiContent.ps1#L180)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $tempPath.FullName 
> ```

Should not have `Fullname` here, it is already taken care of at line 105.
</blockquote></details>

Done.
___
*[source/Public/Publish-WikiContent.ps1, line 113 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKQOvL3ZEaeR9oJQud:-MeQHufoAuCoYaT3l6Gc:b-sm6ys7) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Publish-WikiContent.ps1#L113)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> for ($i=0; $i -lt 20; $i++)
> ```

I don't really see the need for a for-loop here. This seems to just add unnecessary complexity to the function, and just makes it harder to debug. IMHO this looks like bad coding practice. :slightly_smiling_face: 
</blockquote></details>

Since each `Invoke-Git` response must be checked, I didn't want to take the "Nested If" approach as that would look really bad with all of the conditions. Alternatively, I considered refactoring everything, however like database normalization, there comes a point where too much refactoring is unnecessary. So this was my "happy medium" approach. Just like git, your programming-foo is far superior to mine so I'm open to any suggestions. :slig [...]

2021-07-14 10:41 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @johlju and @phbits)

___
*[source/Private/Show-InvokeGitReturn.ps1, line 81 at r1](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeFFOEhAHRzTRMSKOqc:-MeZXIex5IcAEHLZtW2P:bhmbtpr) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b73bb2307d6c348603f6a650646c843d8c228d7c/source/Private/Show-InvokeGitReturn.ps1#L81)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

Good call. :thumbsup: The token should be scrubbed via your regex `if` statement. However, it would be good to ensure the token doesn't get displayed in `StandardOutput` or `StandardError`. I've incorporated this into `Invoke-Git` as noted in the next comment. I could update this section to use the same technique used for `StandardOutput`/`StandardError` (shown below) if you'd like.
</blockquote></details>

Make sure that this command can be used on its own, so it should handle removing the tokens in this function if it could output a command that contain a token. 
___
*[source/Private/Show-InvokeGitReturn.ps1, line 38 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeZZiux8f_Ad75lIMtN:-MeZZiux8f_Ad75lIMtO:bqmrojq) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b7a6d5dab0e0c1e56fb6cad402c032fd7ba9bfa0/source/Private/Show-InvokeGitReturn.ps1#L38)):*
> ```
> Show-InvokeGitReturn
> ```

Maybe rename to `Out-InvokeGitReturn` or `Out-GitResult`. The later will better together with `Invoke-Git`.
___
*[source/Public/Invoke-Git.ps1, line 89 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKTQsA9NNJB-wHQm1e:-MeZWQqo1eDlP6wvM71J:b-wih8jc) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Invoke-Git.ps1#L89)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

You had a good point to scrub any tokens from the command which gave me the idea that `StandardOutput` and `StandardError` should be checked too. I'm not entirely sure if this will catch all interactions of what `git` returns but thought it was a good place to start. Your git-foo is far superior so I'm open to any feedback.

After thinking about this for a bit, `$GitHubToken` should accessible since it's set in the environment. By checking for its presence, we can then check if it's been used.

</blockquote></details>

You must assume the Invoke-Git will be used standalone - on its own, outside of the pipeline, or in a different pipeline. So we can't use environment variable `$GitHubTioken` here

I'm not certain, but maybe we can assume that git does not return the token in any informational, warning, or error message since that would could be logged. Security-wise I think git does not do that, but I'm not certain.

To parse the token we need to use a regex that can find the token, and only the token. The one used at other place in the code assumes the token is part of the GIT URL so we might not be able to use that, if the token is used in other places.

I suggest we don't look for token in the informational, warning, or error messages.
I suggest we move the redacting of the token in the GIT URL to the `Show-InvokeGitReturn`.
___
*[source/Public/Invoke-Git.ps1, line 61 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeZWt052PW9Vr4vwy1P:-MeZWt052PW9Vr4vwy1Q:b-2xpcsj) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b7a6d5dab0e0c1e56fb6cad402c032fd7ba9bfa0/source/Public/Invoke-Git.ps1#L61)):*
> ```
> 'Command'          = $argumentsJoined
> ```

I don''t think we should return the command that is used since it can contain token. And the caller already has the command and does not need it to be returned here.
___
*[source/Public/Publish-WikiContent.ps1, line 113 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKQOvL3ZEaeR9oJQud:-MeZ_Cl8BglQoM1cNMKO:bnd0722) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Publish-WikiContent.ps1#L113)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

Since each `Invoke-Git` response must be checked, I didn't want to take the "Nested If" approach as that would look really bad with all of the conditions. Alternatively, I considered refactoring everything, however like database normalization, there comes a point where too much refactoring is unnecessary. So this was my "happy medium" approach. Just like git, your programming-foo is far superior to mine so I'm open to any suggestions. :slightly_smiling_face:
</blockquote></details>

The main problem is that Invoke-Git does not throw an error, that leads to that we need to have a condition for each `Invoke-Git` call, that would be the proper way here the way the functionality is now. But best was if Invoke-Git actually throw an error when `git` returns an error. So we could teach `Invoke-Git` a new optional parameter that says that it should throw on an error (where exit code is anything other than 0). Then we would only need conditional statements where the caller need to handle different exit codes.


<!-- Sent from Reviewable.io -->

2021-07-14 12:22 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @johlju and @phbits)

___
*[source/Public/Publish-WikiContent.ps1, line 113 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKQOvL3ZEaeR9oJQud:-MeZxHCw1aGbwNILUZJq:b-9w2fhr) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Publish-WikiContent.ps1#L113)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The main problem is that Invoke-Git does not throw an error, that leads to that we need to have a condition for each `Invoke-Git` call, that would be the proper way here the way the functionality is now. But best was if Invoke-Git actually throw an error when `git` returns an error. So we could teach `Invoke-Git` a new optional parameter that says that it should throw on an error (where exit code is anything other than 0). Then we would only need conditional statements where the caller need to handle different exit codes.
</blockquote></details>

Suggest adding a optional parameter `-PassThru` to `Invoke-Git`. If it is passed then `Invoke-Git` returns the hashtable with exit code etc. if it is not passed (the default) then `Invoke-Git` throws when exit code is anything other than 0. 


<!-- Sent from Reviewable.io -->

2021-07-16 00:22 UTC, phbits reviewed
All of the pipeline tests are green though still need to do "real" tests. Thanks for your feedback on this!

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-:-MegfFPFAYq4Hi43LKX7:b-xkzoh2)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @johlju and @phbits)

___
*[source/Public/Invoke-Git.ps1, line 89 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKTQsA9NNJB-wHQm1e:-MegdfwB3ULGiQtOGEc-:b-eh308r) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Invoke-Git.ps1#L89)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You must assume the Invoke-Git will be used standalone - on its own, outside of the pipeline, or in a different pipeline. So we can't use environment variable `$GitHubTioken` here

I'm not certain, but maybe we can assume that git does not return the token in any informational, warning, or error message since that would could be logged. Security-wise I think git does not do that, but I'm not certain.

To parse the token we need to use a regex that can find the token, and only the token. The one used at other place in the code assumes the token is part of the GIT URL so we might not be able to use that, if the token is used in other places.

I suggest we don't look for token in the informational, warning, or error messages.
I suggest we move the redacting of the token in the GIT URL to the `Show-InvokeGitReturn`.
</blockquote></details>

I did as you suggested, however, in regards to the redacted token in GIT URL that too was removed. Replace by including just the first command and up to three characters of the second argument. The aim to ensure tokens aren't mistakenly disclosed since there are appear to be multiple ways to specify a token. 
___
*[source/Public/Invoke-Git.ps1, line 61 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeZWt052PW9Vr4vwy1P:-MeaVrUe3nG8FNFm59HM:b-f8ajco) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b7a6d5dab0e0c1e56fb6cad402c032fd7ba9bfa0/source/Public/Invoke-Git.ps1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'Command'          = $argumentsJoined
> ```

I don''t think we should return the command that is used since it can contain token. And the caller already has the command and does not need it to be returned here.
</blockquote></details>

Ok. I removed it from the returned object. However, I kept a form of it incase an error is thrown to make debugging easier. It will take the first argument and at most the next 3 characters of the second. Figured this would be easier than designing a regex for every possible iteration of a token and its usage. :exploding_head: :slightly_smiling_face: 
___
*[source/Public/Publish-WikiContent.ps1, line 113 at r3](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeKQOvL3ZEaeR9oJQud:-MegeZqc-y-TkkjJIJAf:b764mu7) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/bd234ca585c894ad2c0902ef782ccee237f853ce/source/Public/Publish-WikiContent.ps1#L113)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Suggest adding a optional parameter `-PassThru` to `Invoke-Git`. If it is passed then `Invoke-Git` returns the hashtable with exit code etc. if it is not passed (the default) then `Invoke-Git` throws when exit code is anything other than 0. 
</blockquote></details>

:thumbsup: That turned out much better! Thanks for the feedback!

...I've now got work to do on prior modules. :slightly_smiling_face: 
___
*[source/Private/Show-InvokeGitReturn.ps1, line 38 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeZZiux8f_Ad75lIMtN:-MeaVNo02rJZzDKoE-8a:b-wtup03) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b7a6d5dab0e0c1e56fb6cad402c032fd7ba9bfa0/source/Private/Show-InvokeGitReturn.ps1#L38)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Show-InvokeGitReturn
> ```

Maybe rename to `Out-InvokeGitReturn` or `Out-GitResult`. The later will better together with `Invoke-Git`.
</blockquote></details>

`Out-GitResult`, Done.


<!-- Sent from Reviewable.io -->

2021-07-19 09:56 UTC, johlju requested changes
@phbits this gets better for each iteration :smiley: 

> Reviewed 1 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-:-MeyBSdzE_qRbq3eMk7_:b1aep1q)* status: 1 of 9 files reviewed, 14 unresolved discussions (waiting on @phbits)

___
*[source/Public/Invoke-Git.ps1, line 61 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeZWt052PW9Vr4vwy1P:-MexqkF31PcBkl-VhY0g:b-uxaqnz) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b7a6d5dab0e0c1e56fb6cad402c032fd7ba9bfa0/source/Public/Invoke-Git.ps1#L61)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

Ok. I removed it from the returned object. However, I kept a form of it incase an error is thrown to make debugging easier. It will take the first argument and at most the next 3 characters of the second. Figured this would be easier than designing a regex for every possible iteration of a token and its usage. :exploding_head: :slightly_smiling_face: 
</blockquote></details>


You suggestion might be the right choice. I don't know the various ways of providing a token to a command. We should be able to find a GitHub tokens with the following regex's. But assumes they are the only thing in the string, otherwise it will redact most (all?) of the command. Which could a problematic if there aren't a list of known ways of providing the token. 

Old personal token: `'^[0-9a-f]{40}$'`
New personal token: `^[A-Za-z0-9_]{40}$`

https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/

In that it says that tokens could become up to 255 characters. 

So I think it best to use your version in a separate function (see other comments) that can be enhanced with better handling of tokens, for example if argument is `push` then maybe there are 1 or 2 ways to write a token so it can be redacted correctly and still keep the important (safe) part of the command.
___
*[source/Public/Invoke-Git.ps1, line 43 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexuQWx7PSpuesc-EaO:-MexuQWx7PSpuesc-EaP:bdahgie) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L43)):*
> ```
> Mandatory = $false
> ```

If mandatory is $false we should write it as `[Parameter()]` so it those that are mandatory are more easily seen. Throughout.
___
*[source/Public/Invoke-Git.ps1, line 49 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexuakU8WTUuUIylrOw:-MexuakU8WTUuUIylrOx:bgc5gok) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L49)):*
> ```
>  = $false
> ```

We don't need $false here as a Switch parameter will be $false by default.
___
*[source/Public/Invoke-Git.ps1, line 61 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mey-C76CTbgFyQFAq_B:-Mey-C76CTbgFyQFAq_C:b-7pbsny) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L61)):*
> ```
>         'Command'          = $Arguments[0]
>         'WorkingDirectory' = $WorkingDirectory
> ```

Having these in the hashtable and then removing them from the hashtable at the end of the function does not really help debugging. The variables are already easily available in the debug session. Having them here would just make another contributor think they are used in the code when they are not. :slightly_smiling_face: 
Suggest removing these two from here, and also remove this below:
```
        $gitResult.Remove('Command')
        $gitResult.Remove('WorkingDirectory')
```

We can just build a hashtable to splatt for `Out-GitResult` which is the only use for this, but it is buried deep so it would be better to build a individual splat hashtable for `Out-GitResult`.
___
*[source/Public/Invoke-Git.ps1, line 68 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexsoZw0w3RTkdIs8Mu:-MexsoZw0w3RTkdIs8Mv:b-cqxnf5) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L68)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>     if ([System.String]::IsNullOrWhiteSpace($Arguments[1]) -eq $false)
>     {
>         if ($Arguments[1].Length -gt 3)
>         {
>             $gitResult.Command += " $($Arguments[1].Substring(0,3))..."
>         }
>         else
>         {
>             $gitResult.Command += " $($Arguments[1])..."
>         }
>     }
> ```
</details>


We should move this to `Out-GitRresult` so that it always does this regardless from where `Out-GitResult` is called. Or move it to a helper function (`Hide-GitToken`?) so it can be called from wherever (see comment below).
___
*[source/Public/Invoke-Git.ps1, line 84 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mey6viV1ve-Rms4JhsF:-Mey6viWC9NXEtVoG20d:b-wpibak) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/5be73afb9f439c88c760c47db29e14893698146e/source/Public/Invoke-Git.ps1#L84)):*
> ```
>                 # Remove all new lines at end of string.
>                 $returnValue.StandardOutput = $returnValue.StandardOutput -replace '[\r?\n]+$'
>                 $returnValue.StandardError = $returnValue.StandardError -replace '[\r?\n]+$'
> ```

What was the reason to remove this? If this is not done in `Invoke-Git` the caller needs to do this for each call?
___
*[source/Public/Invoke-Git.ps1, line 119 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexuxZdD5tHIY1SD7YI:-MexuxZdD5tHIY1SD7YJ:bpl2upf) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L119)):*
> ```
> "$($script:localizedData.InvokeGitCommandDebug -f $gitResult.Command)`n" +
> ```

Suggest using the proposed (see other comment)  helper function `Hide-GitToken` (name is up to you ;) and pass in the parameter Arguments.
___
*[source/Public/Invoke-Git.ps1, line 130 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mexr_EoERO8JonrtKl3:-Mexr_EoERO8JonrtKl4:bok6fwb) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L130)):*
> ```
>         $gitResult.Remove('Command')
>         $gitResult.Remove('WorkingDirectory')
> ```

We should remove these, see comment above.
___
*[source/tasks/Publish_GitHub_Wiki_Content.build.ps1, line 206 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mey7ItR1py4Agx_y9eJ:-Mey7ItR1py4Agx_y9eK:b-isxzry) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/tasks/Publish_GitHub_Wiki_Content.build.ps1#L206)):*
> ```
> $remoteURL = $gitRemoteResult.StandardOutput.Replace("`n",'').Replace("`r",'')
> ```

Simpler way to write this would be using regex

```powershell
$remoteURL = $gitRemoteResult.StandardOutput -replace '\r?\n'
```

Code was removed in `Invoke-Git` that handled removal of line breaks at end of string (see other comment in Invoke-Git). 

Though this will remove CR and LF throughout the string `git` will not return the remote URL (the standard output) with line breaks so this isn't really necessary here I think. :thinking: 

If the code in Invoke-Git is added back it should be be enough with 
```powershell
$remoteURL = $gitRemoteResult.StandardOutput
```.
```

___
*[source/Private/Out-GitResult.ps1, line 52 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MextKBg3p8Of96t3WF8:-MextKBg3p8Of96t3WF9:bacjqg8) ([raw file](https://github.com/dsccommunity/dscresource. [...]

2021-07-19 09:58 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96)* status: 1 of 9 files reviewed, 14 unresolved discussions (waiting on @phbits)

___
*[source/Public/Invoke-Git.ps1, line 61 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeZWt052PW9Vr4vwy1P:-MeyBn_-6833VsDqTn5d:b-8on2i) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b7a6d5dab0e0c1e56fb6cad402c032fd7ba9bfa0/source/Public/Invoke-Git.ps1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>


You suggestion might be the right choice. I don't know the various ways of providing a token to a command. We should be able to find a GitHub tokens with the following regex's. But assumes they are the only thing in the string, otherwise it will redact most (all?) of the command. Which could a problematic if there aren't a list of known ways of providing the token. 

Old personal token: `'^[0-9a-f]{40}$'`
New personal token: `^[A-Za-z0-9_]{40}$`

https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/

In that it says that tokens could become up to 255 characters. 

So I think it best to use your version in a separate function (see other comments) that can be enhanced with better handling of tokens, for example if argument is `push` then maybe there are 1 or 2 ways to write a token so it can be redacted correctly and still keep the important (safe) part of the command.
</blockquote></details>

What I meant was, let's start with your version in a separate helper function and build from there. :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2021-07-19 09:59 UTC, johlju commented
Please update (rebase) working branch with latest changes from main branch.

2021-07-21 21:53 UTC, phbits reviewed
build and tests complete successfully. Next, need to do some publishing tests by forklifting it into `/phbits/MyModule` when I can carve out some free time.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-:-Mf9iYLu32JWGpxkbUEn:b-fj87sm)* status: 1 of 11 files reviewed, 13 unresolved discussions (waiting on @johlju)

___
*[source/Public/Invoke-Git.ps1, line 61 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeZWt052PW9Vr4vwy1P:-Mf-B32M0c0ovQG5XtUJ:b-shlsbm) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b7a6d5dab0e0c1e56fb6cad402c032fd7ba9bfa0/source/Public/Invoke-Git.ps1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

What I meant was, let's start with your version in a separate helper function and build from there. :slightly_smiling_face: 
</blockquote></details>

`Hide-GitToken` created. The blog post is very helpful and lead me to the following which seems to work. I'm deferring to you on this one since I don't want my noob-ness to expose tokens. :slightly_smiling_face:

```powershell
PS C:\> 'https://user:ghp_afiu309fkn@github.com/Owner/repo.git' -replace "gh(p|o|u|s|r)_([A-Za-z0-9]{1,255})",'**REDACTED-TOKEN**'
https://user:**REDACTED-TOKEN**@github.com/Owner/repo.git
```
___
*[source/Public/Invoke-Git.ps1, line 43 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexuQWx7PSpuesc-EaO:-Mf-Awk274xiAQZ7ZtNd:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L43)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Mandatory = $false
> ```

If mandatory is $false we should write it as `[Parameter()]` so it those that are mandatory are more easily seen. Throughout.
</blockquote></details>

Done.
___
*[source/Public/Invoke-Git.ps1, line 49 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexuakU8WTUuUIylrOw:-Mf-AygrCFCcoTYr5-dn:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L49)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>  = $false
> ```

We don't need $false here as a Switch parameter will be $false by default.
</blockquote></details>

Done.
___
*[source/Public/Invoke-Git.ps1, line 61 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mey-C76CTbgFyQFAq_B:-Mf-myge94ybsNitdENv:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         'Command'          = $Arguments[0]
>         'WorkingDirectory' = $WorkingDirectory
> ```

Having these in the hashtable and then removing them from the hashtable at the end of the function does not really help debugging. The variables are already easily available in the debug session. Having them here would just make another contributor think they are used in the code when they are not. :slightly_smiling_face: 
Suggest removing these two from here, and also remove this below:
```
        $gitResult.Remove('Command')
        $gitResult.Remove('WorkingDirectory')
```

We can just build a hashtable to splatt for `Out-GitResult` which is the only use for this, but it is buried deep so it would be better to build a individual splat hashtable for `Out-GitResult`.
</blockquote></details>

Done.
___
*[source/Public/Invoke-Git.ps1, line 68 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexsoZw0w3RTkdIs8Mu:-Mf9hYXgEUHh33vVdYyt:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L68)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>     if ([System.String]::IsNullOrWhiteSpace($Arguments[1]) -eq $false)
>     {
>         if ($Arguments[1].Length -gt 3)
>         {
>             $gitResult.Command += " $($Arguments[1].Substring(0,3))..."
>         }
>         else
>         {
>             $gitResult.Command += " $($Arguments[1])..."
>         }
>     }
> ```

We should move this to `Out-GitRresult` so that it always does this regardless from where `Out-GitResult` is called. Or move it to a helper function (`Hide-GitToken`?) so it can be called from wherever (see comment below).
</blockquote></details>

Done.
___
*[source/Public/Invoke-Git.ps1, line 84 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mey6viV1ve-Rms4JhsF:-Mf-nyjg2yPnjddaP-zu:bk6rstj) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/5be73afb9f439c88c760c47db29e14893698146e/source/Public/Invoke-Git.ps1#L84)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                 # Remove all new lines at end of string.
>                 $returnValue.StandardOutput = $returnValue.StandardOutput -replace '[\r?\n]+$'
>                 $returnValue.StandardError = $returnValue.StandardError -replace '[\r?\n]+$'
> ```

What was the reason to remove this? If this is not done in `Invoke-Git` the caller needs to do this for each call?
</blockquote></details>

Yes, having the caller perform this action on the original output. Also found it makes errors and output difficult to read when throwing.
___
*[source/Public/Invoke-Git.ps1, line 119 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexuxZdD5tHIY1SD7YI:-Mf-oFtC9PRDFhchk8Fk:biz7vqw) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L119)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "$($script:localizedData.InvokeGitCommandDebug -f $gitResult.Command)`n" +
> ```

Suggest using the proposed (see other comment)  helper function `Hide-GitToken` (name is up to you ;) and pass in the parameter Arguments.
</blockquote></details>

`Hide-GitToken` :thumbsup:

All I came up with was `Format-GitCommand` :nauseated_face: :slightly_smiling_face: 
___
*[source/Public/Invoke-Git.ps1, line 130 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mexr_EoERO8JonrtKl3:-Mf8lrxn2jOQpUm1GUr4:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L130)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         $gitResult.Remove('Command')
>         $gitResult.Remove('WorkingDirectory')
> ```

We should remove these, see comment above.
</blockquote></details>

Done.
___
*[source/tasks/Publish_GitHub_Wiki_Content.build.ps1, line 206 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mey7ItR1py4Agx_y9eJ:-Mf-rj9p-uJzwX_HwKHu:b-yqtoid) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/tasks/Publish_GitHub_Wiki_Content.build.ps1#L206)):*
> $remoteURL = $gitRemoteResult.StandardOutput -replace '\r?\n'
Switched it back. At the time I wasn't able to get the regex working with tests and thus the string replace. I can't recall the specifics, just happy the regex is working since it's much cleaner.
___
*[source/Private/Out-GitResult.ps1, line 52 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MextKBg3p8Of96t3WF8:-MezJrDTCmMuP1AsT5xy:b163gya) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a [...]

2021-07-26 19:34 UTC, phbits commented
@johlju Just finished testing the module by forklifting it into phbits/MyModule. Wiki publishing worked as expected. 🥳

2021-07-28 14:25 UTC, johlju requested changes
> Reviewed 2 of 9 files at r6, 4 of 8 files at r8, 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @phbits)

___
*[CHANGELOG.md, line 19 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhTKM51xYoRXnNVoIB:-MfhTKM51xYoRXnNVoIC:bbb9oxm) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/CHANGELOG.md#L19)):*
> ```
>   - `Hide-GitToken` - Formats `Invoke-Git` command to be used in Write-Debug &
>     Write-Verbose. Does not reveal token or other authentication methods.
> ```

I think the description should be something like: "Used to redact the token from the specified git command so that the command can be safely outputted in logs."

Depending on other comments below though.
___
*[CHANGELOG.md, line 31 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhUCaxC1WEzlLx7tpV:-MfhUCaxC1WEzlLx7tpW:bi7w70i) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/CHANGELOG.md#L31)):*
> ```
>   - Shows first Argument & at most three characters of subsequent cmd
>     as the command line string in debug messages.
> ```

Is this still true? See other comments.
___
*[source/Public/Invoke-Git.ps1, line 61 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeZWt052PW9Vr4vwy1P:-MfhOZoVC5Zmcx5EOmH3:bxiewgu) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b7a6d5dab0e0c1e56fb6cad402c032fd7ba9bfa0/source/Public/Invoke-Git.ps1#L61)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

`Hide-GitToken` created. The blog post is very helpful and lead me to the following which seems to work. I'm deferring to you on this one since I don't want my noob-ness to expose tokens. :slightly_smiling_face:

```powershell
PS C:\> 'https://user:ghp_afiu309fkn@github.com/Owner/repo.git' -replace "gh(p|o|u|s|r)_([A-Za-z0-9]{1,255})",'**REDACTED-TOKEN**'
https://user:**REDACTED-TOKEN**@github.com/Owner/repo.git
```
</blockquote></details>

I'm just a noob in this case :wink:  I think the regex works, but it need to also handle the old personal token which does not start with 'gh*'. Or have another regex for replacing old tokens (I think there is a grace period before all tokens need to be replaced to new format?). Old regex format `^[0-9a-f]{40}$`.

So it also need to handle 
```
https://user:afiu309fkn@github.com/Owner/repo.git'
```

Might be easiest to just add another regex (replace) after the one you suggested. Then it can be removed when it is no longer needed, in a year or so.

Please add your and my suggestion to `Hide-GitToken` and we go from there.
___
*[source/Public/Invoke-Git.ps1, line 119 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexuxZdD5tHIY1SD7YI:-MfhR9gE5LA1f7pkZ1zd:b-7jk4wr) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L119)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

`Hide-GitToken` :thumbsup:

All I came up with was `Format-GitCommand` :nauseated_face: :slightly_smiling_face: 
</blockquote></details>

Naming is not easy for anyone when trying to just use approved verbs :laughing: I usually struggle too. :slightly_smiling_face: 
___
*[source/Public/Invoke-Git.ps1, line 101 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhUmXc-CZbYv1SVTl_:-MfhUmXc-CZbYv1SVTla:bqe34jo) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/source/Public/Invoke-Git.ps1#L101)):*
> ```
>             $gitResult.Add('Command', $Arguments)
>             $gitResult.Add('WorkingDirectory', $WorkingDirectory)
> ```

We should create a new hashtable and pass that to Out-GitResult so that `Invoke-Git` does not return these to properties when verbose is enabled.
___
*[source/Private/Out-GitResult.ps1, line 52 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MextKBg3p8Of96t3WF8:-MfhLcSNEWFJyURFuatr:b-kvdatm) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Private/Out-GitResult.ps1#L52)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

I tested this prior to implementation and found the string formatter, `-f` will substitute `$null` with an empty string `''` without throwing an error. Using all `$null` values will produce the following though I just updated the function and tests to only allow `$null` for `StandardOutput` and `StandardError`.

```powershell
PS C:\> $testHash = @{ 'ExitCode' = $null; 'StandardOutput' = $null; 'StandardError' = $null; 'Command' = $null; 'WorkingDirectory' = $null }
PS C:\> Out-GitResult @testHash -Verbose -Debug
VERBOSE: git standard output: ''
VERBOSE: git standard error: ''
VERBOSE: git exit code: '0'
DEBUG: Command: git

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: git Working Directory: ''

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
```
</blockquote></details>

Can we add that in a `.NOTES` section in the comment-based help that it is by design and what you said above about substitution. So that other contributors know the design choice. :slightly_smiling_face: 
___
*[source/Private/Out-GitResult.ps1, line 62 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mexu60r2GjhujRjT6Xo:-MfhMFmg8APe0TNGk8lU:b-5qsm6o) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Private/Out-GitResult.ps1#L62)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

Done. 

After re-reading this, `ExitCode` gets declared as `-1`; `WorkingDirectory` shouldn't be `$null` as it's required by `Invoke-Git`; `Command` shouldn't be `$null` either because of `Invoke-Git`. Leaving the "Outputs" as the only properties that could have a `$null` value. Updated those parameters as mandatory and also updated tests.
</blockquote></details>

Out-GitResult can be called from a future function (not just `Invoke-Git`) that does not need nor are interested in the `$WorkingDirectory`, with the current implementation that future function must provide `WorkingDirectory` and `Command` regardless. We should future proof it by allowing `WorkingDirectory` to be optional, same goes for command. Also, the function is called `Out-GitResult`, not `Out-GitResultAndArguments`. Maybe we should have an `Out-GitArguments` that outputs the two parameters `WorkingDirectory` (still optional) and `Command` instead? 

Anyway, let's leave it as is for now. Looks good.
___
*[source/Private/Out-GitResult.ps1, line 14 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhLDrPCeZYml80fxgW:-MfhLDrPCeZYml80fxgX:b-p99yjw) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/source/Private/Out-GitResult.ps1#L14)):*
> ```
> .PARAMETER  StandardError
> ```

Seems there are two spaces here after `.PARAMETER`.
___
*[source/Private/Out-GitResult.ps1, line 24 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhLOnp-fWjrFjQp-Nx:-MfhLOnp-fWjrFjQp-Ny:bn9scaz) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/source/Private/Out-GitResult.ps1#L24)):*
> ```PowerShell
> 
>     .EXAMPLE
> ```

We can remove this blank line.
___
*[source/Private/Show-InvokeGitReturn.ps1, line 81 at r1](https://reviewable.io/reviews/dsccommun [...]

2021-07-28 14:30 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96)* status: 8 of 11 files reviewed, 8 unresolved discussions (waiting on @phbits)

___
*[CHANGELOG.md, line 6 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhW9al3H8WW45sazHE:-MfhW9al3H8WW45sazHF:b-4zogn7) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/CHANGELOG.md#L6)):*
> ```
> ## [Unreleased]
> ```

Please rebase this PR to get latest changes from upstream. Then make sure to move all changelog entries back to the unreleased section. Let me know if you have any issues rebasing.


<!-- Sent from Reviewable.io -->

2021-07-31 05:13 UTC, phbits reviewed
Successfully tested wiki publishing with phbits/MyModule. Debug output redacted the token too! Think we're getting close. :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-:-Mfuy5V-72sNskAqx_4y:bop27yg)* status: 4 of 11 files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[CHANGELOG.md, line 6 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhW9al3H8WW45sazHE:-Mft1ld782etJ-Ek6Spn:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ## [Unreleased]
> ```

Please rebase this PR to get latest changes from upstream. Then make sure to move all changelog entries back to the unreleased section. Let me know if you have any issues rebasing.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 19 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhTKM51xYoRXnNVoIB:-Mft1k_58LarJfjf0mh1:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/CHANGELOG.md#L19)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>   - `Hide-GitToken` - Formats `Invoke-Git` command to be used in Write-Debug &
>     Write-Verbose. Does not reveal token or other authentication methods.
> ```

I think the description should be something like: "Used to redact the token from the specified git command so that the command can be safely outputted in logs."

Depending on other comments below though.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 31 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhUCaxC1WEzlLx7tpV:-Mft24xM0MbiP4KkYXhG:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/CHANGELOG.md#L31)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>   - Shows first Argument & at most three characters of subsequent cmd
>     as the command line string in debug messages.
> ```

Is this still true? See other comments.
</blockquote></details>

Done.
___
*[source/Public/Invoke-Git.ps1, line 61 at r5](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MeZWt052PW9Vr4vwy1P:-MftDteWEPYey7f1lajV:b-qsal9l) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/b7a6d5dab0e0c1e56fb6cad402c032fd7ba9bfa0/source/Public/Invoke-Git.ps1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I'm just a noob in this case :wink:  I think the regex works, but it need to also handle the old personal token which does not start with 'gh*'. Or have another regex for replacing old tokens (I think there is a grace period before all tokens need to be replaced to new format?). Old regex format `^[0-9a-f]{40}$`.

So it also need to handle 
```
https://user:afiu309fkn@github.com/Owner/repo.git'
```

Might be easiest to just add another regex (replace) after the one you suggested. Then it can be removed when it is no longer needed, in a year or so.

Please add your and my suggestion to `Hide-GitToken` and we go from there.
</blockquote></details>

Re-reading the GitHub reference, it notes that new tokens could be up to 255 characters. Updated the regex to `{1,251}` to account for the 4 character prefix.
___
*[source/Public/Invoke-Git.ps1, line 119 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MexuxZdD5tHIY1SD7YI:-MftE8OiDNwWrNAoL-8v:b-k4zzjd) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Public/Invoke-Git.ps1#L119)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Naming is not easy for anyone when trying to just use approved verbs :laughing: I usually struggle too. :slightly_smiling_face: 
</blockquote></details>

:slightly_smiling_face: 
___
*[source/Public/Invoke-Git.ps1, line 101 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhUmXc-CZbYv1SVTl_:-MftFHRw481iA5UQjlJ8:b-tla2e7) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/source/Public/Invoke-Git.ps1#L101)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>             $gitResult.Add('Command', $Arguments)
>             $gitResult.Add('WorkingDirectory', $WorkingDirectory)
> ```

We should create a new hashtable and pass that to Out-GitResult so that `Invoke-Git` does not return these to properties when verbose is enabled.
</blockquote></details>

Wow, good catch! :astonished: :thumbsup: 
___
*[source/Private/Out-GitResult.ps1, line 52 at r7](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MextKBg3p8Of96t3WF8:-Mft4Er66vxiHgF4eiHF:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/969ab62f39f6a86715c207b5a3a674540a27714a/source/Private/Out-GitResult.ps1#L52)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we add that in a `.NOTES` section in the comment-based help that it is by design and what you said above about substitution. So that other contributors know the design choice. :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[source/Private/Out-GitResult.ps1, line 14 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhLDrPCeZYml80fxgW:-Mft2NuC261Y8m8l9yV3:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/source/Private/Out-GitResult.ps1#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> .PARAMETER  StandardError
> ```

Seems there are two spaces here after `.PARAMETER`.
</blockquote></details>

Done.
___
*[source/Private/Out-GitResult.ps1, line 24 at r9](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfhLOnp-fWjrFjQp-Nx:-Mft8Se079sIKgdk6Guq:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/04477785cf1afe153e8c88026254992b68f74908/source/Private/Out-GitResult.ps1#L24)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this blank line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-31 17:58 UTC, johlju requested changes
I will review the last tests as soon as I can.

> Reviewed 3 of 7 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-:-Mfxhmv39F69oZ9B_RdD:b8tuxjc)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @phbits)

___
*[source/Public/Invoke-Git.ps1, line 100 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfxfIWU0tSk1BF8B4za:-MfxfIWU0tSk1BF8B4zb:balibw4) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/source/Public/Invoke-Git.ps1#L100)):*
> ```
> $outGitResultSplat = $gitResult
> ```

This must be `$outGitResultSplat = $gitResult.Clone()` otherwise `$gitResult` will still end up with the added properties.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 23 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfxhUix5jGnNzu_CF8A:-MfxhUix5jGnNzu_CF8B:b-hmina0) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/tests/unit/private/Hide-GitToken.Tests.ps1#L23)):*
> ```
> 'When invoked'
> ```

We could make this a bit more descriptive like "When command contain a GitHub token". See also next comment.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 26 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mfxgnxi-STsYz1JK5LA:-Mfxgnxj2A5apBi23Mtt:b-kl9vjk) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/tests/unit/private/Hide-GitToken.Tests.ps1#L26)):*
> ```
> $legacyToken = (1..40 | %{ ('abcdef1234567890').ToCharArray() | Get-Random }) -join ''
> ```

Maybe we can move this in a separate Context-block "When command contain a legacy GitHub personal access token" so it is more clear what we are testing?
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 27 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mfxg61B3l2zNHVTcq9Z:-Mfxg61B3l2zNHVTcq9_:b16crzi) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/tests/unit/private/Hide-GitToken.Tests.ps1#L27)):*
> ```
> $newTokenLength = Get-Random -Minimum 1 -Maximum 251
> ```

I think we should test a specific length here, otherwise this test will be different on each run. If we want to test all length between 1 and 251 then we should run each length in  test cases (1, 2, 3,... 251).


<!-- Sent from Reviewable.io -->

2021-08-03 20:44 UTC, phbits reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[source/Public/Invoke-Git.ps1, line 100 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfxfIWU0tSk1BF8B4za:-MgCJ6QA568y6F-wKhIK:b-ng08oj) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/source/Public/Invoke-Git.ps1#L100)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $outGitResultSplat = $gitResult
> ```

This must be `$outGitResultSplat = $gitResult.Clone()` otherwise `$gitResult` will still end up with the added properties.
</blockquote></details>

Wow. :astonished: Good catch again! :thumbsup: 

```powershell
PS C:\> $a = @{ 'one' = '1'; 'two' = '2' }
PS C:\> $b = $a
PS C:\> $b.Add('three','3')
PS C:\> $a

Name                           Value
----                           -----
one                            1
three                          3
two                            2
```
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 23 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfxhUix5jGnNzu_CF8A:-MgCKDMT2vnaJsKsOzFT:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/tests/unit/private/Hide-GitToken.Tests.ps1#L23)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'When invoked'
> ```

We could make this a bit more descriptive like "When command contain a GitHub token". See also next comment.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 26 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mfxgnxi-STsYz1JK5LA:-MgCjpsR0H9etLVE94c3:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/tests/unit/private/Hide-GitToken.Tests.ps1#L26)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $legacyToken = (1..40 | %{ ('abcdef1234567890').ToCharArray() | Get-Random }) -join ''
> ```

Maybe we can move this in a separate Context-block "When command contain a legacy GitHub personal access token" so it is more clear what we are testing?
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 27 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mfxg61B3l2zNHVTcq9Z:-MgCjsoD9vatxT1-Nohj:b-pobzvf) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/tests/unit/private/Hide-GitToken.Tests.ps1#L27)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $newTokenLength = Get-Random -Minimum 1 -Maximum 251
> ```

I think we should test a specific length here, otherwise this test will be different on each run. If we want to test all length between 1 and 251 then we should run each length in  test cases (1, 2, 3,... 251).
</blockquote></details>

Suppose`$(1..251) * 5` would be excessive so how about just testing lengths: 1,100,200,255?


<!-- Sent from Reviewable.io -->

2021-08-04 11:25 UTC, johlju requested changes
Just minor style comments left, then I think this is ready to merge.

> Reviewed 2 of 7 files at r10, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-:-MgFu8oz6gXTH4hqN5uD:bl5qif4)* status: all files reviewed, 13 unresolved discussions (waiting on @johlju and @phbits)

___
*[source/Public/Invoke-Git.ps1, line 100 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtS0V96NXItnEX-lI:-MgFtS0V96NXItnEX-lJ:b-5z96pj) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/source/Public/Invoke-Git.ps1#L100)):*
> ```
> clone()
> ```

We should have upper 'C' on the method name `.Clone()`.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 27 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mfxg61B3l2zNHVTcq9Z:-MgFssX5-kGN87UEsfKY:bqqwpb1) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/tests/unit/private/Hide-GitToken.Tests.ps1#L27)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

Suppose`$(1..251) * 5` would be excessive so how about just testing lengths: 1,100,200,255?
</blockquote></details>

Sounds good. We should add the length 40 too since that is what they are today.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 26 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFt2to3kVvH1kuzTQw:-MgFt2to3kVvH1kuzTQx:bcklg1t) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L26)):*
> ```PowerShell
>             $returnedValue = 'remote add origin https://**REDACTED-TOKEN**@github.com/owner/repo.git'
>         }
>         Context 'When command contains a legacy GitHub token' {
> ```

Please add a blank line before this one to add some air in the code.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 30 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtBl-BVBchn5Flz0a:-MgFtBl-BVBchn5Flz0b:bcklg1t) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L30)):*
> ```PowerShell
>                 $legacyToken = (1..40 | %{ ('abcdef1234567890').ToCharArray() | Get-Random }) -join ''
>             }
>             It "Should redact: $legacyToken" {
> ```

Please add a blank line before this one to add some air in the code.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 33 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtIuJ7BQvF3QwiVX-:-MgFtIuJ7BQvF3QwiVX0:bud88tz) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L33)):*
> ```
> Should -Be $true
> ```

We can change this to `Should -BeTrue`. Throughout.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 36 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtC9hDa0rVUvoQ6pu:-MgFtC9hDa0rVUvoQ6pv:bcklg1t) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L36)):*
> ```PowerShell
>             }
>         }
>         Context 'When command contains a GitHub 5 character token' {
> ```

Please add a blank line before this one to add some air in the code.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 54 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtD-276zw4ZPDV5_B:-MgFtD-276zw4ZPDV5_C:bcklg1t) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L54)):*
> ```PowerShell
>             }
>         }
>         Context 'When command contains a GitHub 100 character token' {
> ```

Please add a blank line before this one to add some air in the code.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 72 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtDe_CemcLhs9BxnR:-MgFtDe_CemcLhs9BxnS:bcklg1t) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L72)):*
> ```PowerShell
>             }
>         }
>         Context 'When command contains a GitHub 200 character token' {
> ```

Please add a blank line before this one to add some air in the code.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 90 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtEIt31Hwt3Bj5fnj:-MgFtEIt31Hwt3Bj5fnk:bcklg1t) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L90)):*
> ```PowerShell
>             }
>         }
>         Context 'When command contains a GitHub 255 character token' {
> ```

Please add a blank line before this one to add some air in the code.
___
*[tests/unit/private/Out-GitResult.Tests.ps1, line 101 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtircEfvP1_EGwRPL:-MgFtircEfvP1_EGwRPM:bx9pns9) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Out-GitResult.Tests.ps1#L101)):*
> ```PowerShell
>         Context 'Using custom clone message' {
>             It 'Should write clone message and call expected mocks' {
> ```

Please remove blank line here.
___
*[tests/unit/private/Out-GitResult.Tests.ps1, line 140 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtnUn4aQ8NjhCohHq:-MgFtnUn4aQ8NjhCohHr:bx9pns9) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Out-GitResult.Tests.ps1#L140)):*
> ```PowerShell
>         Context 'Using custom commit message' {
>             It 'Should write commit message and call expected mocks' {
> ```

Please remove blank line here.
___
*[tests/unit/private/Out-GitResult.Tests.ps1, line 179 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtp-eBagKYTghruE1:-MgFtp-eBagKYTghruE2:bx9pns9) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Out-GitResult.Tests.ps1#L179)):*
> ```PowerShell
>         Context 'Using $null property values' {
>             It 'Should call expected mocks' {
> ```

Please remove blank line here.


<!-- Sent from Reviewable.io -->

2021-08-05 03:57 UTC, phbits reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96)* status: 8 of 11 files reviewed, 13 unresolved discussions (waiting on @johlju)

___
*[source/Public/Invoke-Git.ps1, line 100 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtS0V96NXItnEX-lI:-MgI67dE4ufXpjS5XcoL:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/source/Public/Invoke-Git.ps1#L100)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> clone()
> ```

We should have upper 'C' on the method name `.Clone()`.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 23 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MfxhUix5jGnNzu_CF8A:-MgI6DSDA8fay24e97R1:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/tests/unit/private/Hide-GitToken.Tests.ps1#L23)):*
<details><summary><i>Previously, phbits wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 27 at r11](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-Mfxg61B3l2zNHVTcq9Z:-MgI8bPs544HOtsBM9Sk:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dc1efd10888fed9d84a431c7621c6faf9e7ee516/tests/unit/private/Hide-GitToken.Tests.ps1#L27)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Sounds good. We should add the length 40 too since that is what they are today.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 26 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFt2to3kVvH1kuzTQw:-MgI6hy87xlqIjmrX27e:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L26)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a blank line before this one to add some air in the code.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 30 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtBl-BVBchn5Flz0a:-MgJSL0eEsPdLVwCkT9I:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L30)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a blank line before this one to add some air in the code.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 33 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtIuJ7BQvF3QwiVX-:-MgI9sS20s1S1uh6BwSx:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L33)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Should -Be $true
> ```

We can change this to `Should -BeTrue`. Throughout.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 36 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtC9hDa0rVUvoQ6pu:-MgJSIqCDbkGpe1_55d8:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L36)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a blank line before this one to add some air in the code.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 54 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtD-276zw4ZPDV5_B:-MgJSGV15XL_oHVJXn1y:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L54)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a blank line before this one to add some air in the code.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 72 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtDe_CemcLhs9BxnR:-MgJSG778Ch43KPi25GN:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L72)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a blank line before this one to add some air in the code.
</blockquote></details>

Done.
___
*[tests/unit/private/Hide-GitToken.Tests.ps1, line 90 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtEIt31Hwt3Bj5fnj:-MgJSEe5Ao57S6FQhLPM:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Hide-GitToken.Tests.ps1#L90)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a blank line before this one to add some air in the code.
</blockquote></details>

Done.
___
*[tests/unit/private/Out-GitResult.Tests.ps1, line 101 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtircEfvP1_EGwRPL:-MgJSCjBDpNy9iKAE4Kh:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Out-GitResult.Tests.ps1#L101)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please remove blank line here.
</blockquote></details>

Done.
___
*[tests/unit/private/Out-GitResult.Tests.ps1, line 140 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtnUn4aQ8NjhCohHq:-MgJSAeG-T9_kicjoglD:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Out-GitResult.Tests.ps1#L140)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please remove blank line here.
</blockquote></details>

Done.
___
*[tests/unit/private/Out-GitResult.Tests.ps1, line 179 at r12](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-MgFtp-eBagKYTghruE1:-MgJSB1m43lYhypWbH_m:b-896fix) ([raw file](https://github.com/dsccommunity/dscresource.docgenerator/blob/dac606e3f547aed1acab132c026d5d82977511b0/tests/unit/private/Out-GitResult.Tests.ps1#L179)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please remove blank line here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-05 09:11 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.docgenerator/96#-:-MgK_8f0-dGalBJfRhfP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phbits)



<!-- Sent from Reviewable.io -->

2021-08-05 09:11 UTC, merged

2021-08-05 09:12 UTC, johlju commented
Awesome work on this one! 😄